server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 5000ms

  cloud:
    gateway:
      routes:
        # WebSocket Route
        - id: message-service-ws
          uri: lb:ws://message-service
          predicates:
            - Path=/ws/**

        # REST Service Routes
        - id: auth-service
          uri: lb:ws://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

#        - id: message-service
#          uri: lb://message-service
#          predicates:
#            - Path=/api/messages/**
#            - Path=/api/v1/media/**
#          filters:
#            - StripPrefix=0

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
              - X-User-Id
            maxAge: 3600

# Eureka Client Setup (Connects Gateway to all registered services)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true