CREATE TABLE message_table
( msg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id VARCHAR(255),
  receiver_id VARCHAR(255),
  content VARCHAR(5000),
  timestamp TIMESTAMP NOT NULL,
  attachment_url VARCHAR(255),
  attachment_type VARCHAR(255),
  attachment_name VARCHAR(255),
  attachment_size BIGINT,
  is_attachment BOOLEAN NOT NULL DEFAULT FALSE );

CREATE INDEX idx_message_table_sender_receiver
    ON message_table (sender_id, receiver_id);

CREATE INDEX idx_message_table_timestamp
    ON message_table (timestamp);