spring.application.name=chat-service
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat_application}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics,env,mappings,beans,prometheus

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoint.health.show-details=always
management.health.defaults.enabled=true

info.app.name=Chat Service
info.app.description=Real Time Chat Application
info.app.version=1.0.0