spring.application.name=auth-service

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT
jwt.secret=chatAppDevJwtSecretKey2026SecureRandomValue123456789
jwt.expiration=86400000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379