package com.chatapplication.group_chat.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR,
    MESSAGE_NOT_FOUND,
    CONVERSATION_NOT_FOUND,
    GROUP_NOT_FOUND,
    ATTACHMENT_NOT_FOUND,
    REACTION_NOT_FOUND,
    USER_NOT_FOUND,
    USER_PRESENCE_NOT_FOUND,
    INVALID_MESSAGE,
    MESSAGE_ALREADY_DELETED,
    MESSAGE_ALREADY_EDITED,
    FILE_UPLOAD_FAILED
}
